<?php
/**
* @file
* Google Analytics tracking code implementation
*/

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Render\Markup;

/**
 * Implements hook_help().
 */
function googleanalyticsmaster_help($process_name, RouteMatchInterface $route_match) {
  switch ($process_name) {
    case 'help.page.googleanalyticsmaster':
      $output_help = '<h3>' . t('About') . '</h3>';
      $output_help .= '<p>' . t('Google Analytics Master is intended to be simple module that allows administrators to enable and insert Google Analytics tracking into a drupal powered website to generate statistics.') . '</p>';
      $output_help .= '<p>' . t('Google Analytics Master uses the new google analytics api based on https://googletagmanager.com/gtag/js.') . '</p>';
      $output_help .= '<h3>' . t('Options') . '</h3>';
      $output_help .= '<p>' . t('Just insert your web element tracking id in Google Analytics Master settings page.') . '</p>';
      $output_help .= '<h3>' . t('Configuration') . '</h3>';
      $output_help .= '<p>' . t('All settings are available via module settings page, link below.') . '</p>';
      $output_help .= '<p>' . t('Get your tracking id <a href=":ga_url">Google Analytics Website</a>.', [':ga_url' => 'https://www.google.com/analytics/']) . '</p>';
      $output_help .= '<h3>' . t('More') . '</h3>';
      $output_help .= '<p>' . t('Future versions may include google tag manager and the display of statistics via google analytics api.') . '</p>';
      return $output_help;
  }
}

/**
 * Implements page_attachments().
 */
function googleanalyticsmaster_page_attachments(&$page) {
  //get module settings
  $settings = \Drupal::config('googleanalyticsmaster.settings');
  $location = $settings->get('googleanalyticsmaster.location');
  $insertion_type = $settings->get('googleanalyticsmaster.insertion_type');
  $tracking_id = $settings->get('googleanalyticsmaster.tracking_id');
  $tracking_script = $settings->get('googleanalyticsmaster.tracking_script');
  //set spacer
  $tracking_spacer = "'";

  // Build analytics script for web element head.
  $web_element_head = 'https://www.googletagmanager.com/gtag/js?id='.$tracking_id.'';
  $page['#attached']['html_head'][] = [
  [
    '#tag' => 'script',
    '#attributes' => array('src' => $web_element_head),
    '#weight' => '15',
  ],
    'googleanalyticsmaster_web_element_head',
  ];

  // Build analytics script for web element body.
  $web_element_body = 'window.dataLayer = window.dataLayer || [];';
  $web_element_body .= 'function gtag(){dataLayer.push(arguments);}';
  $web_element_body .= 'gtag('.$tracking_spacer.'js'.$tracking_spacer.', new Date());';
  $web_element_body .= 'gtag('.$tracking_spacer.'config'.$tracking_spacer.', '.$tracking_spacer.$tracking_id.$tracking_spacer.');';
 
  $page['#attached']['html_head'][] = [
  [
    '#tag' => 'script',
    '#value' => $web_element_body,
    '#weight' => '16',
  ],
    'googleanalyticsmaster_web_element_body',
  ];
}
